name: Test all platforms

on: [ push, pull_request, merge_group ]

jobs:
  test-linux:
    uses: ./.github/workflows/test.yml
    secrets:
      token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  coveralls:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-linux]
    steps:
    - uses: coverallsapp/github-action@SR-69/ability-to-select-version-of-coverage-reporter-public-issue-170
      with:
        carryforward: "linux-1,linux-2"
        parallel-finished: true
